In [1]:
import pandas as pd

marketing_data = pd.read_csv(
    "data/marketing_campaign.csv",
    sep="\t"
)

print("Kích thước dữ liệu:", marketing_data.shape)

marketing_data.head()

Kích thước dữ liệu: (2240, 29)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [2]:
marketing_data = marketing_data[
    [
        "ID", "Year_Birth", "Education", "Marital_Status",
        "Income", "Kidhome", "Teenhome", "Dt_Customer",
        "Recency", "NumStorePurchases", "NumWebVisitsMonth"
    ]
].copy()

print("Kích thước sau khi chọn cột:", marketing_data.shape)

print("\nKiểu dữ liệu:")
print(marketing_data.dtypes)

print("\nSố giá trị thiếu:")
print(marketing_data.isna().sum())

print("\nSố dòng trùng hoàn toàn:", marketing_data.duplicated().sum())

marketing_data.head()

Kích thước sau khi chọn cột: (2240, 11)

Kiểu dữ liệu:
ID                     int64
Year_Birth             int64
Education             object
Marital_Status        object
Income               float64
Kidhome                int64
Teenhome               int64
Dt_Customer           object
Recency                int64
NumStorePurchases      int64
NumWebVisitsMonth      int64
dtype: object

Số giá trị thiếu:
ID                    0
Year_Birth            0
Education             0
Marital_Status        0
Income               24
Kidhome               0
Teenhome              0
Dt_Customer           0
Recency               0
NumStorePurchases     0
NumWebVisitsMonth     0
dtype: int64

Số dòng trùng hoàn toàn: 0

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5

In [3]:
# Loại bỏ các dòng trùng hoàn toàn
marketing_data_duplicate = marketing_data.drop_duplicates()

print("Kích thước sau khi bỏ trùng:", marketing_data_duplicate.shape)

# Minh họa xóa dòng có nhãn index là 1
marketing_drop_row = marketing_data.drop(labels=[1], axis=0)

print("Kích thước sau khi xóa dòng index 1:", marketing_drop_row.shape)

# Minh họa xóa cột Year_Birth
marketing_drop_column = marketing_data.drop(
    labels=["Year_Birth"],
    axis=1
)

print("Kích thước sau khi xóa cột Year_Birth:", marketing_drop_column.shape)

print("Kích thước marketing_data hiện tại:", marketing_data.shape)

Kích thước sau khi bỏ trùng: (2240, 11)
Kích thước sau khi xóa dòng index 1: (2239, 11)
Kích thước sau khi xóa cột Year_Birth: (2240, 10)
Kích thước marketing_data hiện tại: (2240, 11)

In [4]:
# Kiểm tra các giá trị trước khi thay thế
print("Teenhome ban đầu:")
print(marketing_data["Teenhome"].value_counts().sort_index())

# Tạo cột mới, giữ lại cột gốc
marketing_data["Teenhome_replaced"] = marketing_data["Teenhome"].replace(
    [0, 1, 2],
    ["has no teen", "has teen", "has teen"]
)

print("\nSau khi thay thế:")
print(marketing_data["Teenhome_replaced"].value_counts())

marketing_data[["ID", "Teenhome", "Teenhome_replaced"]].head()

Teenhome ban đầu:
Teenhome
0    1158
1    1030
2      52
Name: count, dtype: int64

Sau khi thay thế:
Teenhome_replaced
has no teen    1158
has teen       1082
Name: count, dtype: int64

     ID  Teenhome Teenhome_replaced
0  5524         0       has no teen
1  2174         1          has teen
2  4141         0       has no teen
3  6182         0       has no teen
4  5324         0       has no teen

In [5]:
# Giữ bản trước khi điền để dùng ở bước dropna()
marketing_before_fill = marketing_data.copy()

# Ghi nhớ những dòng Income bị thiếu
income_missing = marketing_data["Income"].isna()

# Điền giá trị thiếu bằng 0 theo bài mẫu
marketing_data["Income"] = marketing_data["Income"].fillna(0)

# Tạo cột thu nhập kiểu số nguyên
marketing_data["Income_changed"] = marketing_data["Income"].astype(int)

print("Số giá trị đã điền:", income_missing.sum())
print("Số giá trị thiếu còn lại:", marketing_data["Income"].isna().sum())

print("\nKiểu dữ liệu:")
print(marketing_data[["Income", "Income_changed"]].dtypes)

# Xem một số dòng vừa được điền
marketing_data.loc[
    income_missing, ["ID", "Income", "Income_changed"]
].head()

Số giá trị đã điền: 24
Số giá trị thiếu còn lại: 0

Kiểu dữ liệu:
Income            float64
Income_changed      int64
dtype: object

      ID  Income  Income_changed
10  1994     0.0               0
27  5255     0.0               0
43  7281     0.0               0
48  7244     0.0               0
58  8557     0.0               0

In [6]:
# Kiểm tra giá trị thiếu trên bản trước khi điền
print("Giá trị thiếu trước khi loại bỏ:")
print(marketing_before_fill.isna().sum())

# Loại bỏ dòng có ít nhất một giá trị thiếu
marketing_data_withoutna = marketing_before_fill.dropna(how="any")

print("\nKích thước trước khi loại bỏ:", marketing_before_fill.shape)
print("Kích thước sau khi loại bỏ:", marketing_data_withoutna.shape)
print(
    "Số dòng đã loại bỏ:",
    len(marketing_before_fill) - len(marketing_data_withoutna)
)
print(
    "Tổng giá trị thiếu còn lại:",
    marketing_data_withoutna.isna().sum().sum()
)

Giá trị thiếu trước khi loại bỏ:
ID                    0
Year_Birth            0
Education             0
Marital_Status        0
Income               24
Kidhome               0
Teenhome              0
Dt_Customer           0
Recency               0
NumStorePurchases     0
NumWebVisitsMonth     0
Teenhome_replaced     0
dtype: int64

Kích thước trước khi loại bỏ: (2240, 12)
Kích thước sau khi loại bỏ: (2216, 12)
Số dòng đã loại bỏ: 24
Tổng giá trị thiếu còn lại: 0

### Nhận xét kết quả xử lý dữ liệu

- Dữ liệu ban đầu có 2.240 dòng và 29 cột. Sau khi chọn các cột
  theo lab, còn 11 cột.
- Không có dòng trùng hoàn toàn trong dữ liệu đã chọn.
  Vì vậy, drop_duplicates() không làm giảm số dòng.
- Thao tác xóa dòng index 1 và cột Year_Birth được thực hiện
  trên các bản riêng để minh họa, không thay đổi bảng đang dùng.
- Cột Teenhome_replaced có 1.158 khách hàng thuộc nhóm
  "has no teen" và 1.082 khách hàng thuộc nhóm "has teen".
  Cột Teenhome gốc được giữ lại.
- Có 24 giá trị thiếu ở Income. Theo bài mẫu, các giá trị này
  được điền bằng 0; đây là thao tác minh họa, không khẳng định
  thu nhập thực tế của khách hàng bằng 0.
- Cột Income_changed được chuyển sang kiểu số nguyên int64,
  trong khi Income vẫn có kiểu float64.
- Khi áp dụng dropna() trên bản trước khi điền, 24 dòng thiếu
  bị loại bỏ, còn 2.216 dòng và không còn giá trị thiếu.
- Điền giá trị thiếu và loại bỏ dòng thiếu là hai cách xử lý
  được minh họa trên các bản dữ liệu riêng.